[package]
name = "cookie-auth"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "3.0", features = ["tokio"] }
ntex-identity = "3.2.0"
env_logger = "0.11"
