[package]
name = "juniper-example"
version = "3.0.0"
authors = ["pyros2097 <pyros2097@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "3.0.0-pre.6", features = ["tokio"] }
env_logger = "0.11"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.14"
