[package]
name = "juniper-example"
version = "0.4.0"
authors = ["pyros2097 <pyros2097@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "1.0", features = ["tokio"] }
env_logger = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.14"
