[package]
name = "form-example"
version = "3.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "3.0.0-pre.6", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
