[package]
name = "form-example"
version = "2.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.2", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
