[package]
name = "server-sent-events"
version = "2.0.0"
authors = ["Arve Seljebu"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.0-beta.0", features = ["tokio"] }
env_logger = "0.10"
futures = "0.3"
tokio = { version = "1", features = ["sync"] }