[package]
name = "server-sent-events"
version = "3.0.0"
authors = ["Arve Seljebu"]
edition = "2018"

[dependencies]
ntex = { version = "3.0", features = ["tokio"] }
env_logger = "0.11"
futures = "0.3"
tokio = { version = "1", features = ["sync"] }