[package]
name = "openssl-example"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.1.7", features = ["openssl"] }
env_logger = "0.7"
openssl = "0.10"
