[package]
name = "error_handling"
version = "2.0.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.0-beta.0", features = ["tokio"] }
derive_more = "0.99"
futures = "0.3"
rand = "0.8"
env_logger = "0.10"
