[package]
name = "websocket-example"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "websocket-chat-server"
path = "src/main.rs"

[dependencies]
ntex = "0.1.15"
ntex-files = "0.1.0"

rand = "0.7"
bytes = "0.5.4"
byteorder = "1.1"
futures = "0.3.4"
env_logger = "0.7"
serde = "1.0"
serde_json = "1.0"
