[package]
name = "template_handlebars"
version = "3.0.0"
authors = ["Alexandru Tiniuc <tiniuc.alexandru@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "3.0.0-pre.6", features = ["tokio"] }
handlebars = { version = "3.0.0", features = ["dir_source"] }
serde_json = "1.0"
