[package]
name = "async_ex2"
version = "0.1.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
ntex = "0.3"
bytes = "1.0"
env_logger = "0.8"
futures = "0.3"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.1"
