[package]
name = "async_ex2"
version = "0.2.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.0-beta.0", features = ["tokio"] }
env_logger = "0.10"
futures = "0.3"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3"
