[package]
name = "async_ex2"
version = "3.0.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "3.0.0-pre.6", features = ["tokio"] }
env_logger = "0.11"
futures = "0.3"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3"
