[package]
name = "cookie-session"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.7.0", features = ["tokio"] }
ntex-session = "0.3"
futures = "0.3"
time = "0.3"
env_logger = "0.10"
