[package]
name = "cookie-session"
version = "3.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "3.0", features = ["tokio"] }
ntex-session = "3.2.0"
futures = "0.3"
time = "0.3"
env_logger = "0.11"
