[package]
name = "middleware-example"
version = "3.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>", "Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "3.0.0-pre.9", features = ["tokio"] }
env_logger = "0.11"
futures = "0.3"
pin-project = "1.0"
