[package]
name = "jsonrpc-example"
version = "2.0.0"
authors = ["mohanson <mohanson@outlook.com>"]
edition = "2018"

[dependencies]
ntex = "0.1.7"
bytes = "0.5"
env_logger = "0.7"
futures = "0.3.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
