[package]
name = "template-tera"
version = "3.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.10"
tera = "1.0"
ntex = { version = "0.6.2", features = ["tokio"] }
