[package]
name = "template-askama"
version = "3.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.7.0", features = ["tokio"] }
askama = "0.9"

[build-dependencies]
askama = "0.9"
